// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAESbHjmALYvjk8bWpLWs21lpTlwojD9r8',
    appId: '1:806638526502:web:05298b53d642b1682486e7',
    messagingSenderId: '806638526502',
    projectId: 'racetracker-a6b37',
    authDomain: 'racetracker-a6b37.firebaseapp.com',
    databaseURL: 'https://racetracker-a6b37-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'racetracker-a6b37.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb35F690pHG_tAZQHnRE2vfy33yvHpTZ0',
    appId: '1:806638526502:android:e47e575bda30777a2486e7',
    messagingSenderId: '806638526502',
    projectId: 'racetracker-a6b37',
    databaseURL: 'https://racetracker-a6b37-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'racetracker-a6b37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPyrPm5eV6udXfCVSFpphwIAsnI3Du2GQ',
    appId: '1:806638526502:ios:e3178e131f12da1e2486e7',
    messagingSenderId: '806638526502',
    projectId: 'racetracker-a6b37',
    databaseURL: 'https://racetracker-a6b37-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'racetracker-a6b37.firebasestorage.app',
    iosBundleId: 'com.example.raceTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPyrPm5eV6udXfCVSFpphwIAsnI3Du2GQ',
    appId: '1:806638526502:ios:e3178e131f12da1e2486e7',
    messagingSenderId: '806638526502',
    projectId: 'racetracker-a6b37',
    databaseURL: 'https://racetracker-a6b37-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'racetracker-a6b37.firebasestorage.app',
    iosBundleId: 'com.example.raceTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAESbHjmALYvjk8bWpLWs21lpTlwojD9r8',
    appId: '1:806638526502:web:9d7a19babad6cd972486e7',
    messagingSenderId: '806638526502',
    projectId: 'racetracker-a6b37',
    authDomain: 'racetracker-a6b37.firebaseapp.com',
    databaseURL: 'https://racetracker-a6b37-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'racetracker-a6b37.firebasestorage.app',
  );
}
